# Generated by Django 4.1.7 on 2023-02-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
