# Generated by Django 4.1.7 on 2023-02-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_id_alter_employee_econtact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
    ]
